<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <RootNamespace>Loan_Calculator_Suite</RootNamespace>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="frontend\Class1.cs" />
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Remove="frontend\Class1.resx" />
  </ItemGroup>

</Project>
